### ISSUE TITLE
Is there a way to retrieve events in a synchronous manner?

### ISSUE THREAD

**Issue by joshua-nicholson** [robertmrk/aiosfstream#15]
I am needing to run this within a lambda in AWS. Due to costs, this isn't something I can run indefinitely, and am attempting to schedule my code to run, receive all of the platform events since the previous run, and then close the connection. How can I accomplish this?

**Comment by joshua-nicholson** [comment]
After digging into Salesforce docs, it seems that the streaming API was not built to be used in a synchronous manner.

**Comment by joshua-nicholson** [comment]
After digging into Salesforce docs, it seems that the streaming API was not built to be used in a synchronous manner.

**Comment by blakev** [comment]
You can save your place using the `replay` functionality.  I created a `DynamoDBReplay(ReplayMarkerStorage)` that would get/save the replayID. You could run your lambda on an interval and as long as it runs every ~24h the events should still be saved in SalesForce.

**Comment by joshua-nicholson** [comment]
The issue is the way the streaming API (and as a result this library) works is that you have to keep the client open the whole time. There doesn't seem to be a way to open the connection, collect events using the replayId, and then immediately close the connection once those are done being collected. It stays open waiting for more events.

**Comment by blakev** [comment]
I'm telling you it works because I'm doing it right now. If this is something you need don't give up.

SalesForce will hold the events for 24 hours after they happen. As long as you have the last ReplayID that your application received it can get all the events it missed, up to 24 hours, every time it runs.

![Untitled(1)](https://user-images.githubusercontent.com/4885156/105876677-6e108980-5fbc-11eb-9f95-31b9696ad497.jpg)

The block of JSON lines is my application catching up after being offline for 8 hours. Then you can see sporadic JSON lines every few minutes below it.

I can't share my code because I'm under contract.

**Comment by joshua-nicholson** [comment]
Maybe you can tell me what's wrong with my code here? The behavior I'm seeing is that once all events from the past 24 hours have been processed, the client remains open until lambda kills it, as lambdas have a maximum execution time of 15 minutes. I want to close the connection and stop the lambda as soon as all previous events have been processed, not wait for lambda to kill the process as that's needlessly expensive.

```
async def stream_events():
        async with SalesforceStreamingClient(
            username=sf_username,
            password=sf_password,
            consumer_key=sf_consumer_key,
            consumer_secret=sf_consumer_secret,
            sandbox=True,
            replay=ReplayOption.ALL_EVENTS
        ) as sf_client:
            await sf_client.subscribe("/event/New_Account__e")
            aws_client = boto3.client("sns")
            sns_arn = f"arn:aws:sns:us-east-1:{aws_account_number}:sf-lead-conversion-{environment}"

            async for message in sf_client:
                topic = message["channel"]
                data = message["data"]
                data["payload"]["event_type"] = "lead_conversion"
                print(f"{topic}: {data}")
                response = aws_client.publish(
                    TargetArn=sns_arn,
                    Message=(json.dumps({"default": json.dumps(data["payload"])})),
                    MessageStructure="json",
                )
                print(response)

    asyncio.run(stream_events())
```

**Comment by blakev** [comment]
I see we got stuck on the same part :) https://stackoverflow.com/questions/65241741/what-is-the-correct-way-to-combine-async-for-with-an-if-condition-to-break-mid-a

My code looks like this, 
```python
# create two tasks, wait for the first one to finish
messages_task = asyncio.create_task(iterate_msgs(client))
shutdown_task = asyncio.create_task(self.stop_event.wait())

# wait for all the messages to be processed, or when the shutdown
#  event has been set. Either way we need to start cleaning up the
# start task for a graceful shutdown.
await asyncio.wait(
    [
        messages_task,
        shutdown_task,
    ],
    return_when=asyncio.FIRST_COMPLETED,
)

if shutdown_task.done():
    messages_task.cancel()
elif messages_task.done():
    shutdown_task.cancel()

```

But you could just as easily say,

```python
shutdown_task = asyncio.create_task(asyncio.sleep(60.0))
```

..which would break the `async for` loop after 1 minute.

**Comment by joshua-nicholson** [comment]
Oh nice, so the first task completes once all of the initial messages it receives are done? That's awesome.

**Comment by blakev** [comment]
Right!

Which ever task completes first will break the `asyncio.wait`. Since `async for message in client` is infinite the `asyncio.sleep` will always be the killer. My breaker is an `asyncio.Event` which gets set when a shutdown signal is detected.

**Comment by joshua-nicholson** [comment]
@blakev Is there a way to shutdown the client gracefully? I am seeing the following in my logs.

```
[ERROR]	2021-01-27T22:29:40.696Z	4860c9f3-2d18-4af5-ab9b-56f1a42b2af5	Exception in callback TransportBase._connect_done(<Task cancell.../utils.py:22>>)
handle: <Handle TransportBase._connect_done(<Task cancell.../utils.py:22>>)>
Traceback (most recent call last):
  File "/var/lang/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/var/task/aiocometd/transports/base.py", line 541, in _connect_done
    result: Union[JsonObject, Exception] = future.result()
asyncio.exceptions.CancelledErrorEND RequestId: 4860c9f3-2d18-4af5-ab9b-56f1a42b2af5
```

**Comment by blakev** [comment]
@joshua-nicholson 

Yes! You can use operating system signals. This is a good guide on how to attach signals to the event loop and trigger a `shutdown` coroutine that will cleanup all the pending tasks nicely. 

https://www.roguelynn.com/words/asyncio-graceful-shutdowns/

```python
async def shutdown(sig: int, workers: List[Worker], loop: AbstractEventLoop):
    """Cleanup tasks tied to the service's shutdown."""

    logger.info('shutting down')

    for worker in workers:
        await worker.stop()

    tasks = [t for t in asyncio.all_tasks() if t is not asyncio.current_task()]

    for task in tasks:
        task.cancel()

    await asyncio.gather(*tasks)
    loop.stop()
```

```python
    # bind shutdown signals
    signals = (
        signal.SIGHUP,
        signal.SIGTERM,
        signal.SIGINT,
    )
    for sig in signals:
        loop.add_signal_handler(
            sig, lambda s=sig: asyncio.create_task(shutdown(s, workers, loop))
        )
```

**Comment by joshua-nicholson** [comment]
@blakev Sorry to ask again, but you basically did the exact same thing I'm attempting and your answers have been extremely helpful so far. I'm not quite understanding how to use the `replay` param when setting up the client. I'm just going to be retrieving/saving this value to s3, so I don't need to do any sort of custom implementation of ReplayMarkerStorage. 

I just want to be able to send the replay ID into this param, and according to the docs I should be able to use a `dict` to do so but it doesn't work for me, it seems to not recognize what I'm doing and defaults it to only listening for new events. The issue is the docs say the `dict` would be in this format `[str, ReplayMarker]` but do not say what this string needs to be.

I tried this hardcoded based on values from a previous event `replay={"replay": ReplayMarker(date="2021-01-27T18:33:17.861Z, replay_id=272624')}`. Do you know how to simply pass in a replay ID without implementing ReplayMarkerStorage?

**Comment by blakev** [comment]
This is what I do... I've also done it with DynamoDB

The most reliable way, that I've found, is to just persist your Shelve database to S3 and restore it on start up. So, using these two commands the first thing I do is download the old one, and save it when my program is shutting down -- or periodically since mine isn't short lived like yours. Using Lambda it should be pretty painless to save the DB to /tmp, load from there as the documentation does, and save the closed file back to S3 before the handler exits.

```python
    def get_s3_replay(self) -> None:
        """Downloads the Shelve record from S3 and overwrites the local copy."""
        try:
            resp = self.s3.get_object(
                Bucket=self.worker_config.aws.bucket_name,
                Key=f'{BUCKET_ROOT}/{self.db_name}'
            )
        except ClientError as e:
            if e.response['Error']['Code'] == 'NoSuchKey':
                logger.info('no shelve db found in s3')
            else:
                raise
        else:
            with open(self.db_path, 'wb') as fp:
                fp.write(resp['Body'].read())
            logger.info('successful s3 replay download')

    async def set_s3_replay(self) -> None:
        """Uploads the Shelve record to S3, overwriting the remote copy."""
        try:
            f_size = os.stat(self.db_path).st_size

            with open(self.db_path, 'rb') as fp:
                kwargs = dict(
                    Bucket=self.worker_config.aws.bucket_name,
                    Body=fp,
                    ContentLength=f_size,
                    Key=f'{BUCKET_ROOT}/{self.db_name}',
                )
                fn = partial(self.s3.put_object, **kwargs)
                resp = await self.loop.run_in_executor(None, fn)

        except ClientError as e:
            logger.exception(e)
            resp = {}

        if resp.get('ETag'):
            logger.info('successful s3 replay upload')
        else:
            logger.warning('unsuccessful s3 replay upload')
```

**Comment by efv824** [comment]
Hi @joshua-nicholson and @blakev,

I’ve been going over your code and it’s been super helpful. My code is very similar to joshua-nicholson’s post on January 26, 2021 (attached below). I am attempting to gracefully shutdown the stream of messages after the client has streamed  previous messages. 

I am having difficulty incorporating the shutdown_task as well as the shutdown coroutine. I’m not sure where to place the single line shutdown_task or the shutdown coroutine- are they supposed to go in the main function to run the coroutine or in the stream_events function?

**Marker Storage Function**
```
async def FulfillmentOrder_LocalReplayMarkerStorage():
	client = bigquery.Client()
	query = """
		SELECT DISTINCT event_createdDate, replayId 
		FROM dw.table
		WHERE replayId = (SELECT MAX(replayId) FROM dw.table) 
		"""
	query_job = client.query(query) 
	result = query_job.result() # Waits for job to complete.
	for row in result:
		# Row values can be accessed by field name or index.
		marker = ReplayMarker(date=row['event_createdDate'], replay_id=row['replayId'])
		print(marker)
	return marker
```

**Stream Events function**
```
async def stream_events_FulfillmentOrder():
	replay = {"replay": FulfillmentOrder_LocalReplayMarkerStorage()}

	# connect to Streaming API
	async with SalesforceStreamingClient(
		consumer_key=client_id,
		consumer_secret=client_secret,
		username=username,
		password=f'{password}{security_token}',
		# json_dumps=ujson.dumps,
		# json_loads=ujson.loads
		sandbox=True,
		replay=replay,
		replay_fallback=ReplayOption.ALL_EVENTS,
		#replay_storage_policy=ReplayMarkerStoragePolicy.MANUAL
		) as client:
			# subscribe to topics
			await client.subscribe("/topic/FulfillmentOrder")
			# listen for incoming messages
			try: 
				async for message in client:
					topic = message["channel"]
					data = message["data"]
					print(f"{topic}: {data}")
					if message["channel"] == '/topic/FulfillmentOrder':
						# store values in variables
						value1 = data['sobject']['value1']
						value2 = data['sobject']['value2']
						value3 = data['sobject']['value3']
						value4 = data['sobject']['value4']
						# store variables in an array
						lst = [value1, value2, value3, value4]
						# store array in a dataframe
						df.pd.DataFrame([lst], columns = ['value1', 'value2', 'value3', 'value4'])
						# push data to BQ 
			except TransportTimeoutError:
				# datetime object containing current date and time
				now = datetime.now()
				print(f"{now}: Connection is lost with the server. Couldn't reconnect in 60 seconds. \n TransportTimeoutError('Lost connection with the server.')")
```

**Main Function**
```
def main_FulfillmentOrder():
    loop = asyncio.get_event_loop()
    loop.run_until_complete(stream_events_FulfillmentOrder())
```
