### ISSUE TITLE
Passing a dictionary to the replay param?

### ISSUE THREAD

**Issue by joshua-nicholson** [robertmrk/aiosfstream#16]
The docs say you can use a dictionary to pass the `replay` param of the client.

> replay (Union[ReplayOption, ReplayMarkerStorage, Mutablemapping[str, ReplayMarker]]) – A ReplayOption or an object capable of storing replay ids if you want to take advantage of Salesforce’s replay extension. You can use one of the ReplayOptions, or an object that supports the MutableMapping protocol like dict, defaultdict, Shelf etc. or a custom ReplayMarkerStorage implementation.

I'm not exactly clear on what this dictionary needs to contain though. I see it needs a string and a `ReplayMarker` so I tried this

`replay={"replay": ReplayMarker("2021-01-27T18:33:19.087Z", 272625)}`

But I don't seem to pull in any previous events. These are hardcoded for now for testing purposes, I'll dynamically retrieve them from the last successful event once I get this working.

**Comment by ghost** [comment]
I was experiencing the same issue, I know this is a year old but still!

I got it working doing this, unsure if it's the intended way:
```
from aiosfstream import SalesforceStreamingClient, ReplayOption, DefaultMappingStorage

replay = DefaultMappingStorage({}, self.max_stored_replay_id)
logging.info(f'Retrieving Messages since replay_id: {self.max_stored_replay_id}')

client = SalesforceStreamingClient(consumer_key=self.consumer_key,
                                                            consumer_secret=self.consumer_secret,
                                                            username=self.username,
                                                            password=self.password,
                                                            sandbox=self.sandbox,
                                                            replay=replay,
                                                            replay_fallback=ReplayOption.NEW_EVENTS
                                           )
```
I'm storing the replay_id and checking it on client creation.

**Comment by welcomemat-services** [comment]
@charlie-peak-ai I am using my own ReplayMarkerStorage and having issues with retrieving events by passing a replay id stored in pgsql. I believe, I have followed all required steps yet if pull the last stored replay id and pass it, it is throwing an exception. I have created a new issue here, please let me know if you see any thing unusual in my code.

https://github.com/robertmrk/aiosfstream/issues/19#issue-1126620196

**Comment by joshua-nicholson** [comment]
Thank you @charlie-peak-ai! I just had to revisit this now almost two years later from my original question and I was able to get it to work using the code you provided.
