### ISSUE TITLE
Is there a way to manuallu specify replayId without creating complex instances and implementations of `ReplayMarkerStorage` or 'Mutablemapping'

### ISSUE THREAD

**Issue by pranayjswl007** [robertmrk/aiosfstream#9]
I just wanna specify replayId when I create an connect , is there an easier way?

**Comment by robertmrk** [comment]
Hi @pranayjswl007 

If you just want to always retrieve new events or all events from the retention window then you can either pass `ReplayOption.NEW_EVENTS` or `ReplayOption.ALL_EVENTS` to the `replay` parameter of the [Client](https://aiosfstream.readthedocs.io/en/latest/api.html#client).
But if you want your client to start retrieving events from the point where it left off then you *must* pass an object to the `replay` parameter which either has a [MutableMapping](https://docs.python.org/3/library/collections.abc.html#collections.abc.MutableMapping) or a [ReplayMarkerStorage](https://aiosfstream.readthedocs.io/en/latest/api.html#aiosfstream.ReplayMarkerStorage) interface. 
It is explained in the [Replay configuration](https://aiosfstream.readthedocs.io/en/latest/advanced.html#replay-configuration) section.

To create a custom [ReplayMarkerStorage](https://aiosfstream.readthedocs.io/en/latest/api.html#aiosfstream.ReplayMarkerStorage) class, all you have to do is to implement `set_replay_marker` and `get_replay_marker`. Or if you don't want to create a custom class for storing replay ids, it doesn't get much simpler then passing a [Shelf](https://docs.python.org/3/library/shelve.html#shelve.Shelf) object to the `replay` parameter.

**Comment by joshua-nicholson** [comment]
@pranayjswl007 Did you figure this out? I'm in the same situation as you right now. The docs say you can just use a `dict` but then don't show what the shape of the dictionary needs to be, so I don't know what to do.
